# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 16:24
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('photoes', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
